### PR TITLE
Update pod spec version

### PR DESCRIPTION
**Pull request by mendesbarreto**
Hello @HHK1,

I just adjusted the pod spec can you upload it to COCOAPODS, please? 

And I added to changelog the fix of CSTime to NSValue casting, because is a brake change on XCode 12 and will be easier to see this if someone using an old version of your lib.

Thank you so much.

Douglas

### CODE REVIEW

**Comment by mendesbarreto** [comment]
I almost forget, the lib YPImagePicker is using cocoapods to distribute the version 4.0.0, so for the one who needs to update to Xcode 12 like me, this little guy is braking things

**Review by M-I-N — APPROVED** [review]

**Comment by HHK1** [comment]
hi @mendesbarreto thanks for your PR and the reminder to publish the update :) I went ahead and published the version on CocoaPods and Carthage

**Comment by petrykDima** [comment]
After update to PryntTrimmerView 4.0.2 it fix some problems but created new =)

Screenshot 2020-09-18 at 10 45 40

**Comment by M-I-N** [comment]
@petrykDima this is not related to [PryntTrimmerView](https://github.com/HHK1/PryntTrimmerView). See the [earlier comment](https://github.com/HHK1/PryntTrimmerView/pull/70#issuecomment-694325077) by @mendesbarreto

**Comment by petrykDima** [comment]
@M-I-N So, we should just wait for a merge this fix ?

**Comment by M-I-N** [comment]
@petrykDima yes, [YPImagePicker](https://github.com/Yummypets/YPImagePicker) needs to take this update and merge there.

**Comment by fukemy** [comment]
hi, waiting for your update,  i got this error when update new xcode for ios 14

**Comment by sdowless** [comment]
Still waiting for a fix on this. Any update?

**Pull request closed without merging**
